id: P004575
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:42:26.322647
source_metadata:
  id: bdr:W27298
  title: ཐུགས་རྗེ་ཆེན་པོའི་དམར་ཁྲིད་ངེས་དོན་དཔྱིད་ཀྱི་ཐིག་ལེ
  author: ''
  volumes:
    2a2f9e41b9aa4658ad67b2df93479cdf:
      image_group_id: I4196
      title: ''
      volume_number: 1
      total_pages: 60
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
